In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 200)

In [2]:
df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)
df.head()

(590540, 394)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,M1,M2,M3,M4,M5,M6,M7,M8,M9,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,V29,V30,V31,V32,V33,V34,V35,V36,V37,V38,V39,V40,V41,V42,V43,V44,V45,...,V240,V241,V242,V243,V244,V245,V246,V247,V248,V249,V250,V251,V252,V253,V254,V255,V256,V257,V258,V259,V260,V261,V262,V263,V264,V265,V266,V267,V268,V269,V270,V271,V272,V273,V274,V275,V276,V277,V278,V279,V280,V281,V282,V283,V284,V285,V286,V287,V288,V289,V290,V291,V292,V293,V294,V295,V296,V297,V298,V299,V300,V301,V302,V303,V304,V305,V306,V307,V308,V309,V310,V311,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321,V322,V323,V324,V325,V326,V327,V328,V329,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,14.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,NaN,NaN,NaN,0.0,T,T,T,M2,F,T,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,M0,T,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,315.0,NaN,NaN,NaN,315.0,T,T,T,M0,F,F,F,F,F,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,NaN,2.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,1.0,112.0,112.0,0.0,94.0,0.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,NaN,111.0,NaN,NaN,NaN,M0,T,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,28.0,0.0,0.0,0.0,0.0,10.0,0.0,4.0,0.0,0.0,1.0,1.0,1.0,1.0,38.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,50.0,1758.0,925.0,0.0,354.0,0.0,135.0,0.0,0.0,0.0,50.0,1404.0,790.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df.info()
df.isnull().mean().sort_values(ascending=False).head(20)

<class 'pandas.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), str(14)
memory usage: 1.7 GB

dist2    0.936284
D7       0.934099
D13      0.895093
D14      0.894695
D12      0.890410
D6       0.876068
D9       0.873123
D8       0.873123
V153     0.861237
V149     0.861237
V141     0.861237
V146     0.861237
V154     0.861237
V162     0.861237
V142     0.861237
V158     0.861237
V161     0.861237
V157     0.861237
V138     0.861237
V139     0.861237
dtype: float64

In [4]:
# Comportamento Temporal
# Hipótese: A fraude muitas vezes acontece em horários atípicos, como de madrugada.
# Pergunta: A transação aconteceu rápido demais?
temporal_features = {}

temporal_features["hour"] = (df["TransactionDT"] // 3600) % 24
temporal_features["day"] = df["TransactionDT"] // 86400
temporal_features["week"] = df["TransactionDT"] // (86400 * 7)

In [5]:
# Features de velocidade em que ocorre as transações
df = df.sort_values(["card1", "TransactionDT"])

temporal_features["time_since_last"] = (
    df.groupby("card1")["TransactionDT"].diff()
)

temporal_features["fast_txn_flag"] = (
    temporal_features["time_since_last"] < 300
).astype(int)

df = pd.concat(
    [df, pd.DataFrame(temporal_features, index=df.index)],
    axis=1
)

In [6]:
df["dist1"] = df["dist1"].fillna(-1)

# Comportamento Geográfico
# Hipótese: Transações fraudulentas frequentemente apresentam inconsistências de localização e distância geográfica.
# Pergunta: A transação aconteceu em um local incomum para o usuário?
geo_features = {}

geo_features["card1_addr_freq"] = (
    df.groupby(["card1", "addr1"])["card1"]
    .transform("count")
)

geo_features["card1_mean_dist"] = (
    df.groupby("card1")["dist1"]
    .transform("mean")
)

geo_features["dist1_vs_card1_mean"] = (
    df["dist1"] - geo_features["card1_mean_dist"]
)

previous_addr = df.groupby("card1")["addr1"].shift(1)

geo_features["addr_change"] = (
    (df["addr1"] != previous_addr) &
    previous_addr.notnull()
).astype(int)

geo_features["dist1_missing"] = df["dist1"].isnull().astype(int)

df = pd.concat(
    [df, pd.DataFrame(geo_features, index=df.index)],
    axis=1
)

In [7]:
# Comportamento Monetário
# Hipótese: Transações fraudulentas podem apresentar padrões de valor atípicos.
# Pergunta: O valor da transação é incomum para o usuário?
amount_features = {}

amount_features["log_amount"] = np.log1p(df["TransactionAmt"])

amount_features["card1_amt_mean"] = (
    df.groupby("card1")["TransactionAmt"]
    .transform("mean")
)

amount_features["card1_amt_std"] = (
    df.groupby("card1")["TransactionAmt"]
    .transform("std")
)

amount_features["amt_vs_card1_mean"] = (
    df["TransactionAmt"] - amount_features["card1_amt_mean"]
)

amount_features["amt_zscore_card1"] = (
    amount_features["amt_vs_card1_mean"] /
    (amount_features["card1_amt_std"] + 1e-6)
)

df = pd.concat(
    [df, pd.DataFrame(amount_features, index=df.index)],
    axis=1
)

In [8]:
# Comportamento Identificador
# Hipótese: Fraudes muitas vezes envolvem inconsistências nos atributos de identificação.
# Pergunta: A identidade parece inconsistente?
identity_features = {}

identity_features["card1_freq"] = (
    df["card1"].map(df["card1"].value_counts())
)

identity_features["email_domain_change"] = (
    df["P_emaildomain"] != df["R_emaildomain"]
).astype(int)

df = pd.concat(
    [df, pd.DataFrame(identity_features, index=df.index)],
    axis=1
)

In [9]:
df["card4"] = df["card4"].astype("category")
df["card6"] = df["card6"].astype("category")

In [10]:
df = df.loc[:, ~df.columns.duplicated()]

In [11]:
new_features = [
    "hour", "day", "week",
    "time_since_last", "fast_txn_flag",
    "addr_change",
    "card1_addr_freq",
    "dist1_vs_card1_mean",
    "log_amount",
    "amt_vs_card1_mean",
    "amt_zscore_card1",
    "card1_freq",
    "email_domain_change"
]

df[new_features].head()

,hour,day,week,time_since_last,fast_txn_flag,addr_change,card1_addr_freq,dist1_vs_card1_mean,log_amount,amt_vs_card1_mean,amt_zscore_card1,card1_freq,email_domain_change
243924,23,66,9,NaN,0,0,NaN,0.0,3.196344,0.000000,NaN,1,0
36634,14,10,1,NaN,0,0,3.0,8.0,5.214936,103.333333,1.154628,3,1
164336,13,40,5,2587912.0,0,0,3.0,-4.0,3.401197,-50.666667,-0.566140,3,1
223739,0,61,8,1766278.0,0,0,3.0,-4.0,3.332205,-52.666667,-0.588488,3,1
33767,18,9,1,NaN,0,0,1.0,0.0,5.017280,13.600000,0.145334,5,1

In [12]:
df[new_features].isnull().mean().sort_values(ascending=False)

card1_addr_freq        0.111264
time_since_last        0.022950
amt_zscore_card1       0.005832
hour                   0.000000
day                    0.000000
fast_txn_flag          0.000000
week                   0.000000
dist1_vs_card1_mean    0.000000
addr_change            0.000000
log_amount             0.000000
amt_vs_card1_mean      0.000000
card1_freq             0.000000
email_domain_change    0.000000
dtype: float64

In [13]:
df["amt_zscore_card1"] = (
    df["amt_zscore_card1"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

A análise dos valores ausentes das novas features mostrou que o pipeline de feature engineering apresentou boa consistência geral, já que a maioria das variáveis criadas não possui valores nulos. As features temporais (hour, day, week e fast_txn_flag) e monetárias (log_amount e amt_vs_card1_mean) foram geradas integralmente, indicando que as transformações aplicadas sobre TransactionDT e TransactionAmt foram bem-sucedidas. 

Já a feature time_since_last apresentou cerca de 2,3% de valores ausentes, o que é esperado, pois a primeira transação de cada cartão não possui uma transação anterior para comparação temporal. A variável amt_zscore_card1 apresentou apenas 0,58% de valores nulos, provavelmente associados a cartões com poucas transações, dificultando o cálculo do desvio padrão. A feature card1_addr_freq foi a que apresentou maior percentual de valores ausentes (11,1%), possivelmente devido à ausência de informações em addr1 para algumas transações.

De forma geral, os resultados indicam que as novas features foram construídas com boa qualidade e baixo nível de perda de informação, tornando o conjunto de dados mais rico para a etapa de modelagem preditiva de fraude.

In [ ]:
df.to_csv("transaction_features.csv", index=False)

#### Behavioral Consistency Features
Fraudulent behavior often combines abnormal timing, monetary deviation and geographic inconsistency.

In [14]:
consistency_features = {}

# Pergunta:
# O valor atual é muito diferente da transação anterior?

previous_amount = (
    df.groupby("card1")["TransactionAmt"]
    .shift(1)
)

consistency_features["amt_ratio_prev"] = (
    df["TransactionAmt"] /
    (previous_amount + 1e-6)
)

consistency_features["amt_ratio_prev"] = (
    consistency_features["amt_ratio_prev"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(1)
)

# Pergunta:
# O valor atual é muito diferente da média das últimas 5 transações?

rolling_mean_5 = (
    df.groupby("card1")["TransactionAmt"]
    .transform(
        lambda x: x.shift(1).rolling(5).mean()
    )
)

consistency_features["amt_ratio_last5"] = (
    df["TransactionAmt"] /
    (rolling_mean_5 + 1e-6)
)

consistency_features["amt_ratio_last5"] = (
    consistency_features["amt_ratio_last5"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(1)
)

# Pergunta:
# Esse cartão transacionou rápido demais?

consistency_features["high_velocity_flag"] = (
    df["time_since_last"] < 300
).astype(int)

# Pergunta:
# O cartão mudou de endereço muito rapidamente?

consistency_features["rapid_addr_change"] = (
    (df["time_since_last"] < 300) &
    (df["addr_change"] == 1)
).astype(int)

# Pergunta:
# A compra foi muito rápida e o valor é estranho?

consistency_features["rapid_large_txn"] = (
    (df["time_since_last"] < 300) &
    (df["amt_zscore_card1"] > 3)
).astype(int)

# Pergunta:
# Houve mudança geográfica e valor estranho?

consistency_features["geo_amount_anomaly"] = (
    (df["addr_change"] == 1) &
    (df["amt_zscore_card1"] > 3)
).astype(int)

df = pd.concat(
    [df, pd.DataFrame(consistency_features, index=df.index)],
    axis=1
)